### ISSUE TITLE
BRD Ring of Law 

### ISSUE THREAD

**Issue by Taemeluch** [renegadewow/Renegade-WoW#141] opened 2018-05-13 17:21 UTC
Description:
Ring of Law event in BRD will make the first spawn. After Spawn death, the NPC will do his monologue, then nothing happens

Current behaviour:
CHANGEME Tell us what happens.

Expected behaviour Please include links to your source (for ex. wowhead.com):
BRD is supposed to have 3 waves from what I remember in the Rule of Law Event

Steps to reproduce the problem:
1. I just started the event, 
Useful links (ex; youtube.com):

**Comment by Cillez** [comment] 2018-05-13 17:43
Duplicate of issue #115

**Closed by Cillez** 2018-05-13 17:43 UTC
